name: face-gen-pipeline
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch
  - torchvision
  - torchaudio
  - pip
  - pip:
    - fastapi
    - uvicorn
    - onnxruntime
    - boto3
    - mlflow
    - scikit-learn
    - ruff
    - black
    - pre-commit
    - pytest
    - requests
    - pydantic
